platform_mapping = {
    '3do interactive multiplayer': '3do',
    '3do': '3do',
    '64dd': '64d',
    'acorn archimedes': 'ros',
    'amiga 1200': 'a12',
    'amiga cdtv': 'acd',
    'amiga': 'ami',
    'amstrad cpc': 'acp',
    'android': 'and',
    'apple ii': 'ap2',
    'apple iigs': 'a2g',
    'apple tv': 'atv',
    'arcade': 'arc',
    'archimedes': 'ros',
    'arduboy': 'ard',
    'atari 8-bit': 'a8b',
    'atari 2600': 'a26',
    'atari 5200': 'a52',
    'atari 7800': 'a78',
    'atari jaguar': 'jag',
    'atari lynx': 'lyn',
    'atari st': 'ast',
    'bbc micro': 'bbc',
    'brew': 'bre',
    'cd32': 'c32',
    'classic mac os': 'mac',
    'coleco mini-arcade': 'cma',
    'colecovision': 'col',
    'commodore 64': 'c64',
    'desqview': 'dqv',
    'dos': 'dos',
    'electron': 'ele',
    'epoc32': 'ep3',
    'fairchild channel f': 'fcf',
    'famicom/nes': 'nes',
    'fire os': 'fir',
    'fm towns': 'fmt',
    'fm-7': 'fm7',
    'game & watch': 'gaw',
    'game boy advance': 'gba',
    'game boy color': 'gbc',
    'game boy': 'gby',
    'game gear': 'sgg',
    'gamecube': 'gcn',
    'google stadia': 'gst',
    'ibm pc': 'ibm',
    'intellivision': 'int',
    'ios': 'ios',
    'ique player': 'que',
    'irix': 'iri',
    'j2me': 'j2m',
    'jaguar': 'jag',
    'java me': 'jme',
    'linux': 'lin',
    'mac os': 'mac',
    'macintosh': 'mac',
    'macos': 'mac',
    'magnavox odyssey 2': 'mo2',
    'master system': 'sms',
    'mega drive': 'gen',
    'mega duck': 'mgd',
    'microsoft windows': 'win',
    'ms-dos': 'dos',
    'msx': 'msx',
    'neo geo cd': 'ncd',
    'neo geo pocket color': 'npc',
    'neo geo pocket': 'ngp',
    'neo geo': 'ngx',
    'nes': 'nes',
    'new nintendo 3ds': 'n3d',
    'nextstep': 'nst',
    'nintendo 64': 'n64',
    'nintendo 3ds': '3ds',
    'nintendo ds': 'nds',
    'nintendo dsi (dsiware)': 'dsi',
    'nintendo e-reader': 'ner',
    'nintendo entertainment system': 'nes',
    'nintendo switch': 'swi',
    'nvidia shield tv': 'nst',
    'olpc xo-1': 'olp',
    'os x': 'mac',
    'os/2': 'os2',
    'pc engine cd-rom²': 'tcd',
    'pc engine super cd-rom²': 'tsc',
    'pc-88': 'p88',
    'pc-98': 'p98',
    'pc-fx': 'pfx',
    'philips cd-i': 'cdi',
    'playstation 2': 'ps2',
    'playstation 3': 'ps3',
    'playstation 4': 'ps4',
    'playstation 5': 'ps5',
    'playstation portable': 'psp',
    'playstation vita': 'psv',
    'playstation': 'ps1',
    'pokemon mini': 'pkm',
    'raspberry pi': 'rpi',
    'risc os': 'ros',
    'sam coupé': 'sam',
    'satellaview': 'stv',
    'sega 32x': '32x',
    'sega cd': 'scd',
    'sega saturn': 'sat',
    'sg-1000': 'sg1',
    'sharp x1': 'sx1',
    'sharp x68000': 'x68',
    'snes': 'sfc',
    'solaris': 'sol',
    'super nes': 'sfc',
    'super nintendo entertainment system': 'sfc',
    'ti-99/4a': 't99',
    'turbografx-16': 't16',
    'tvos': 'atv',
    'unix': 'lin',
    'vectrex': 'vec',
    'vic-20': 'v20',
    'virtual boy': 'vby',
    'wasm-4': 'wa4',
    'watara supervision': 'wsv',
    'wii u': 'wiu',
    'wii': 'wii',
    'windows': 'win',
    'windows phone': 'wph',
    'wonderswan': 'wsn',
    'wonderswan color': 'wsc',
    'xbox': 'xbx',
    'xbox 360': 'x36',
    'xbox one': 'xb1',
    'xbox series x/s': 'xsx',
    'zx spectrum': 'zxs'
}

platform_information = {
    '3do': ('Panasonic', '3DO', 'Console'),
    '3ds': ('Nintendo', '3DS', 'Handheld'),
    '32x': ('Sega', '32X', 'Console Addon'),
    '64d': ('Nintendo', '64DD', 'Console Addon'),
    'a2g': ('Apple', '2 GS', 'Computer'),
    'a8b': ('Atari', '8-Bit', 'Computer'),
    'a12': ('Commodore', 'Amiga 1200', 'Computer'),
    'a26': ('Atari', '2600', 'Console'),
    'a52': ('Atari', '5200', 'Console'),
    'a78': ('Atari', '7800', 'Console'),
    'acd': ('Commodore', 'Amiga CD-TV', 'Console'),
    'acp': ('Amstrad', 'CPC', 'Computer'),
    'ami': ('Commodore', 'Amiga', 'Computer'),
    'and': ('Google', 'Android', 'Mobile'),
    'ap2': ('Apple', '2', 'Computer'),
    'arc': ('Various', 'Arcades', 'Console'),
    'ard': ('Kevin Bates', 'Arduboy', 'Handheld'),
    'ast': ('Atari', 'ST', 'Computer'),
    'atv': ('Apple', 'TV', 'Mobile'),
    'bbc': ('BBC', 'Micro', 'Computer'),
    'bre': ('Qualcomm', 'BREW', 'Computer'),
    'c32': ('Commodore', 'Amiga CD-32', 'Console'),
    'c64': ('Commodore', '64', 'Computer'),
    'cdi': ('Philips', 'CD-i', 'Console'),
    'cma': ('Coleco', 'Mini-Arcade', 'Console'),
    'col': ('Coleco', 'ColecoVision', 'Console'),
    'dos': ('Various', 'DOS', 'Computer'),
    'dqv': ('Quarterdeck', 'DESQview', 'Computer'),
    'dsi': ('Nintendo', 'DSiWare', 'Handheld'),
    'ele': ('Acorn', 'Electron', 'Computer'),
    'ep3': ('Psion', 'EPOC-32', 'Computer'),
    'fcf': ('Fairchild', 'Channel F', 'Console'),
    'fir': ('Amazon', 'Fire OS', 'Mobile'),
    'fm7': ('Fujitsu', 'FM-7', 'Computer'),
    'fmt': ('Fujitsu', 'FM Towns', 'Computer'),
    'gaw': ('Nintendo', 'Game & Watch', 'Handheld'),
    'gba': ('Nintendo', 'Game Boy Advance', 'Handheld'),
    'gbc': ('Nintendo', 'Game Boy Color', 'Handheld'),
    'gbx': ('Nintendo', 'Game Boy', 'Handheld'),
    'gcn': ('Nintendo', 'GameCube', 'Console'),
    'gen': ('Sega', 'Genesis', 'Console'),
    'gst': ('Google', 'Stadia', 'Console'),
    'ibm': ('IBM', 'PC', 'Computer'),
    'int': ('Mattel', 'Intellivision', 'Console'),
    'ios': ('Apple', 'iOS', 'Mobile'),
    'iri': ('Silicon Graphics', 'IRIX', 'Computer'),
    'j2m': ('Various', 'Java ME', 'Computer'),
    'jag': ('Atari', 'Jaguar', 'Console'),
    'jme': ('Various', 'Java ME', 'Computer'),
    'lin': ('Unix', 'Linux', 'Computer'),
    'lyn': ('Atari', 'Lynx', 'Handheld'),
    'mac': ('Apple', 'MacOS', 'Computer'),
    'mgd': ('Welback', 'Mega Duck', 'Handheld'),
    'mo2': ('Magnavox', 'Odyssey 2', 'Computer'),
    'msx': ('ASCII', 'MSX', 'Computer'),
    'n3d': ('Nintendo', 'New 3DS', 'Handheld'),
    'n64': ('Nintendo', 'Nintendo 64', 'Console'),
    'ncd': ('SNK', 'Neo Geo CD', 'Console'),
    'nds': ('Nintendo', 'DS', 'Handheld'),
    'ner': ('Nintendo', 'e-Reader', 'Handheld'),
    'nes': ('Nintendo', 'Nintendo Entertainment System', 'Console'),
    'ngp': ('SNK', 'Neo Geo Pocket', 'Handheld'),
    'ngx': ('SNK', 'Neo Geo', 'Console'),
    'npc': ('SNK', 'Neo Geo Pocket Color', 'Handheld'),
    'nst': ('NVIDIA', 'Shield TV', 'Computer'),
    'nxp': ('NeXT', 'NeXTSTEP', 'Computer'),
    'olp': ('Quanta', 'OLPC XO', 'Computer'),
    'os2': ('IBM', 'OS/2', 'Computer'),
    'p88': ('NEC', 'PC-8800', 'Computer'),
    'p98': ('NEC', 'PC-9800', 'Computer'),
    'pfx': ('NEC', 'PC-FX', 'Computer'),
    'pkm': ('Nintendo', 'Pokemon Mini', 'Handheld'),
    'ps1': ('Sony', 'PlayStation', 'Console'),
    'ps2': ('Sony', 'PlayStation 2', 'Console'),
    'ps3': ('Sony', 'PlayStation 3', 'Console'),
    'ps4': ('Sony', 'PlayStation 4', 'Console'),
    'ps5': ('Sony', 'PlayStation 5', 'Console'),
    'psp': ('Sony', 'PlayStation Portable', 'Handheld'),
    'psv': ('Sony', 'PlayStation Vita', 'Handheld'),
    'que': ('iQue', 'Player', 'Console'),
    'ros': ('Acorn', 'RISC OS', 'Computer'),
    'rpi': ('Raspberry Pi Foundation', 'Pi', 'Computer'),
    'sam': ('Miles Gordon Technology', 'SAM Coupé', 'Computer'),
    'sat': ('Sega', 'Saturn', 'Console'),
    'scd': ('Sega', 'CD', 'Console Addon'),
    'sfc': ('Nintendo', 'Super Nintendo', 'Console'),
    'sg1': ('Sega', 'SG-1000', 'Console'),
    'sgg': ('Sega', 'Game Gear', 'Handheld'),
    'sms': ('Sega', 'Master System', 'Console'),
    'sol': ('Oracle', 'Solaris', 'Computer'),
    'stv': ('Nintendo', 'Satellaview', 'Console Addon'),
    'swi': ('Nintendo', 'Switch', 'Console'),
    'sx1': ('Sharp', 'X1', 'Computer'),
    't99': ('Texas Instruments', '99/4A', 'Computer'),
    't16': ('NEC', 'TurboGrafx-16', 'Console'),
    'tcd': ('NEC', 'TurboGrafx-CD', 'Console Addon'),
    'tsc': ('NEC', 'TurboGrafx Super CD', 'Console Addon'),
    'v20': ('Commodore', 'VIC-20', 'Computer'),
    'vby': ('Nintendo', 'Virtual Boy', 'Handheld'),
    'vec': ('General Consumer Electronics', 'Vectrex', 'Console'),
    'wa4': ('aduros', 'WASM-4', 'Computer'),
    'wii': ('Nintendo', 'Wii', 'Console'),
    'win': ('Microsoft', 'Windows', 'Computer'),
    'wiu': ('Nintendo', 'Wii U', 'Console'),
    'wph': ('Microsoft', 'Windows Phone', 'Mobile'),
    'wsc': ('Bandai', 'WonderSwan Color', 'Handheld'),
    'wsn': ('Bandai', 'WonderSwan', 'Handheld'),
    'wsv': ('Watara', 'Supervision', 'Handheld'),
    'x36': ('Microsoft', 'Xbox 360', 'Console'),
    'x68': ('Sharp', 'X68000', 'Computer'),
    'xb1': ('Microsoft', 'Xbox One', 'Console'),
    'xbx': ('Microsoft', 'Xbox', 'Console'),
    'xsx': ('Microsoft', 'Xbox Series X/S', 'Console'),
    'zxs': ('Sinclair Research', 'ZX Spectrum', 'Computer')
}


def platform_conv(systems):
    # Iterate over each platform in the systems list and map it to its corresponding shortened platform name
    return [platform_mapping.get(platform.lower(), platform) for platform in systems]
